import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from 'next/font/google';
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import { getAutenticatedhUser } from "@/lib/getAuthUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

export default async function RootLayout({ children }) {
  const authUser=await getAutenticatedhUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <div>
          <NavBar authUser={authUser}/>
        </div>
        <main className="flex-grow">
          {children}
        </main>
        <div className="py-4 bg-gray-100 text-center text-sm text-gray-600"><Footer /></div>
      </body>
    </html>
  );
}
